### ISSUE TITLE
🔧 [기능요청][FCM] FCM 알림 서비스

### ISSUE THREAD

**Issue by Chuseok22** [Team-TicketMate/ticketmate-server#104]
🗒️ 설명
---
FCM 토큰
Firebase Cloud Messaging (FCM) 입니다
구글에서 지원해주는 무료 서비스예요

- Firebase Admin SDK를 사용하여 Spring 에서 FCM을 통해 알림 전송 기능 구현
- 클라이언트로부터 FCM 토큰을 수집하고 관리
- 알림 전송을 위한 API 엔드포인트 생성
- 보안 및 환경 설정 강화

1. **Gradle 의존성 추가**
   - `firebase-admin` SDK 추가
   - JSON 처리 라이브러리 추가

2. **서비스 계정 키 설정**
   - `src/main/resources`에 `firebase-service-account.json` 파일 추가
   - `.gitignore`에 해당 파일 경로 추가

3. **Firebase 초기화 구성**
   - `FirebaseConfig` 클래스 작성 및 Firebase 초기화 로직 구현

4. **FCM 메시지 전송 서비스 구현**
   - `FcmService` 클래스 작성
   - 알림 메시지 생성 및 전송 로직 구현

5. **API 엔드포인트 작성**
   - `NotificationController` 작성
   - 알림 전송을 위한 POST API 구현

6. **클라이언트와의 연동**
   - 클라이언트에서 FCM 토큰 수집 및 백엔드로 전송 로직 구현 (별도 이슈로 분리 필요)

7. **보안 강화**
   - 서비스 계정 키 관리 방안 검토 및 적용
   - 환경 변수 설정

8. **테스트 및 디버깅**
   - 단위 테스트 및 통합 테스트 작성
   - 실제 알림 전송 테스트 수행

제가 구현할때 작성된 이슈 끌어온거라 실제 구현방식과는 조금 차이가 있을 수 있습니다.

🙋‍♂️ 담당자
---
- 백엔드: @mr6208

**Comment by Chuseok22** [comment]
### FIrebase가 초기화되지 않는 문제

![Image](https://github.com/user-attachments/assets/392bba0d-dec8-4293-b2d7-c560c5a51911)

서버 로그를 살펴보니 다음과 같은 문제가 발생했습니다

로컬에서 실행했을때는 분명히 정상적으로 실행되는데 서버에서는 오류가 발생하기에 gitsecret에 등록되어있는 key.json파일을 확인했습니다

key.json파일은 

```
-----------PRIVATE_KEY------------
DKFJDKFJKDJFKJFK~~~~
DFKJDKFJF~~~
----------END_KEY------------
```
와 같은 형식으로 작성되어있습니다
하지만 저장되어있는 key.json파일 같은 경우 실제 엔터로 줄바꿈을 구현하지 않고 개행문자 (\n)을 사용합니다

따라서 gitsecret에 등록되어있는 json파일을 실제 src/.../resources에 등록할때 다음과 같이 등록됩니다

![Image](https://github.com/user-attachments/assets/c0a17144-a0ed-4cbe-ba92-9740e563699e)


### 해결
리눅스 sed를 사용하여 파일을 파싱할때 개행문자를 엔터로 변환하도록 하였습니다

`sed `s/찾을문자/바꿀문자`` 이렇게 사용하면 됩니다
또한 마지막에 g를 붙이지 않으면 첫번째 문자만 변경하게됩니다

### 추가 문제 발생
여전히 개행문자 문제가 해결되지않아 추가로 검색한 결과
git secret에 등록된 파일을 바로 사용하는경우 문제가 생기는 걸 확인했습니다
따라서 환경변수로 먼저 받은 뒤, 해당 변수에 들어있는 값을 파싱하는 방식으로 변경했습니다

```
      # firebase sdk 파일을 빌드 전에 생성 (문자열 내의 \n을 실제 개행문자로 변경)
      - name: Create ticketmate-firebase-key.json from secret
        env:
          FIREBASE_KEY_JSON: ${{ secrets.TICKETMATE_FIREBASE_KEY_JSON }}
        run: |
          echo "$FIREBASE_KEY_JSON" | sed 's/\n/\n/g' > ./src/main/resources/ticketmate-firebase-key.json
```
