### ISSUE TITLE
⚙️ [기능추가][CI] feat 브랜치에서 PR 수행 시 build 테스트

### ISSUE THREAD

**Issue by Chuseok22** [Team-TicketMate/ticketmate-server#11]
🗒️ 설명
---
### `TICKET_MATE-BE-CICD`
```
name: TICKET-MATE-BE-CICD
on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
```
* 현재 main, test브랜치에 push 또는 main 브랜치로 pr이 올라가면 자동 CI/CD가 진행됩니다
* 하지만 워크플로우 상 push는 feat브랜치에만 이루어지며 main브랜치에 pr을 올리기 전에는 build 과정이 제대로 진행되는지 알 수 없습니다
* 따라서 test 브랜치에 pr 요청이 이루어지면 build과정만 검토하는 기능을 추가하려고합니다
* 시간을 단축하고자 build 과정만 테스트합니다

### `TICKET-MATE-BE-CICD``
```
name: TICKET-MATE-BE-PR-BUILD

on:
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # application-prod.yml 파일을 빌드 전에 생성
      - name: Create application-prod.yml from secret
        run: |
          echo "${{ secrets.APPLICATION_PROD_YML }}" > ./src/main/resources/application-prod.yml

      # prod 프로파일을 활성화하여 빌드 ( 테스트 코드 테스트 X )
      - name: Build with Gradle
        run: ./gradlew clean build -x test -Dspring.profiles.active=prod
```

🙋‍♂️ 담당자
---
- 백엔드: @Chuseok22 
- 프론트엔드: 이름
- 디자인: 이름
