### ISSUE TITLE
🔧 [기능요청][CICD] GitHub Action을 사용한 자동 CI/CD 워크플로우 추가

### ISSUE THREAD

**Issue by Chuseok22** [Team-TicketMate/ticketmate-server#3]
🗒️ 설명
---
### 사용 이유
개발 프로세스를 간소화하고 일관성을 확보하기 위해 GitHub Action을 활용한 CI/CD 파이프라인을 구현해야 합니다
코드 변경 사항이 저장소에 반영될 때마다 테스트(test), 빌드(build), 배포(deploy) 과정을 자동화합니다

### 구현 방법
GitHub Actions 워크플로우 파일 `.github/workflows/` 경로에 `TICKET_MATE_BE_CICD.yaml`파일이 존재합니다
해당 파일에 코드를 작성하면 됩니다

1. 트리거 이벤트
  * `main` 브랜치에 대한 `push`이벤트 발생 시 워크플로우 실행
  * `test` 브랜치에 대한 `push` 이벤트 발생 시 워크플로우 실행
2. 작업
  * 환경 설정
    * `ubuntu-latest` 사용
    * 의존성 설치 (필요시)
  * 애플리케이션 빌드 (build)
  * 배포 (deploy)

### 특이 사항
* application.yml (git 등록 O), application-dev.yml (git 등록X), application-prod.yml (git 등록X)
* yaml 파일을 분리하기 때문에 `application-prod.yml`파일을 GitHub Secret에 등록하여 빌드 전 생성해야합니다
* Ci/CD 파일은 GitHub에 등록되기 때문에 민감한 정보는 GitHub Secret를 활용하여 환경변수 설정을 진행해야합니다

### Sample Code
```
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v3

    - name: Java 설정
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: 의존성 설치
      run: |
        ./gradlew dependencies

    - name: 테스트 실행
      run: |
        ./gradlew test

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v3

    - name: 스테이징 배포
      run: |
        ./deploy-scripts/staging-deploy.sh

    - name: 프로덕션 배포 (수동 승인)
      if: github.event_name == 'push'
      uses: hmarr/auto-approve-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
```

🙋‍♂️ 담당자
---
- 백엔드: @mr6208 @Chuseok22 
- 프론트엔드: 이름
- 디자인: 이름
